apiVersion: v1
kind: Service
metadata:
  name: sec-eng-challenge-service
spec:
  type: NodePort 
  selector:
    app: sec-eng-challenge
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30009